version: '3.8'

services:
  # web:
  #   image: nginx:1.19
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./public:/usr/share/nginx/html:ro
  node:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: npx webpack serve --host 0.0.0.0 # allow connections from everywhere
    ports:
      - 8080:8080
  back:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./server:/app
    command: ["npx", "nodemon", "src"]
    ports:
      - 3000:3000
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: pepa-linha
    ports:
      - 8081:8080
